export const data = {
  films: [
    {
      docId: 1,
      genre: 'children',
      slug: 'frozen',
      title: 'frozen',
      description: 'frozen',
    },
    {
      docId: 2,
      genre: 'children',
      slug: 'despicable-me',
      title: 'despicable-me',
      description: 'despicable-me',
    },
    {
      docId: 3,
      genre: 'children',
      slug: 'hotel-transylvania',
      title: 'hotel-transylvania',
      description: 'hotel-transylvania',
    },
    {
      docId: 4,
      genre: 'children',
      slug: 'spirited-away',
      title: 'spirited-away',
      description: 'spirited-away',
    },
    {
      docId: 5,
      genre: 'children',
      slug: 'up',
      title: 'up',
      description: 'up',
    },
    {
      docId: 6,
      genre: 'drama',
      slug: 'fight-club',
      title: 'fight-club',
      description: 'fight-club',
    },
    {
      docId: 7,
      genre: 'drama',
      slug: 'kings-speech',
      title: 'kings-speech',
      description: 'kings-speech',
    },
    {
      docId: 8,
      genre: 'drama',
      slug: 'the-prestige',
      title: 'the-prestige',
      description: 'the-prestige',
    },
    {
      docId: 9,
      genre: 'drama',
      slug: 'the-revenant',
      title: 'the-revenant',
      description: 'the-revenant',
    },
    {
      docId: 10,
      genre: 'drama',
      slug: 'the-social-network',
      title: 'the-social-network',
      description: 'the-social-network',
    },
    {
      docId: 11,
      genre: 'romance',
      slug: 'a-star-is-born',
      title: 'a-star-is-born',
      description: 'a-star-is-born',
    },
    {
      docId: 12,
      genre: 'romance',
      slug: 'blue-valentine',
      title: 'blue-valentine',
      description: 'blue-valentine',
    },
    {
      docId: 13,
      genre: 'romance',
      slug: 'la-la-land',
      title: 'la-la-land',
      description: 'la-la-land',
    },
    {
      docId: 14,
      genre: 'romance',
      slug: 'the-notebook',
      title: 'the-notebook',
      description: 'the-notebook',
    },
    {
      docId: 15,
      genre: 'romance',
      slug: 'titanic',
      title: 'titanic',
      description: 'titanic',
    },
    {
      docId: 16,
      genre: 'suspence',
      slug: 'gone-girl',
      title: 'gone-girl',
      description: 'gone-girl',
    },
    {
      docId: 17,
      genre: 'suspence',
      slug: 'prisoners',
      title: 'prisoners',
      description: 'prisoners',
    },
    {
      docId: 18,
      genre: 'suspence',
      slug: 'seven',
      title: 'seven',
      description: 'seven',
    },
    {
      docId: 19,
      genre: 'suspence',
      slug: 'shutter-island',
      title: 'shutter-island',
      description: 'shutter-island',
    },
    {
      docId: 20,
      genre: 'suspence',
      slug: 'zodiac',
      title: 'zodiac',
      description: 'zodiac',
    },
    {
      docId: 21,
      genre: 'thriller',
      slug: 'a-quiet-place',
      title: 'a-quiet-place',
      description: 'a-quiet-place',
    },
    {
      docId: 22,
      genre: 'thriller',
      slug: 'black-swan',
      title: 'black-swan',
      description: 'black-swan',
    },
    {
      docId: 23,
      genre: 'thriller',
      slug: 'joker',
      title: 'joker',
      description: 'joker',
    },
    {
      docId: 24,
      genre: 'thriller',
      slug: 'nightcrawler',
      title: 'nightcrawler',
      description: 'nightcrawler',
    },
    {
      docId: 25,
      genre: 'thriller',
      slug: 'the-silence-of-the-lambs',
      title: 'the-silence-of-the-lambs',
      description: 'the-silence-of-the-lambs',
    },
  ],
  series: [
    {
      docId: 1,
      genre: 'children',
      slug: 'dora-the-explorer',
      title: 'dora-the-explorer',
      description: 'dora-the-explorer',
    },
    {
      docId: 2,
      genre: 'children',
      slug: 'peppa-pig',
      title: 'peppa-pig',
      description: 'peppa-pig',
    },
    {
      docId: 3,
      genre: 'children',
      slug: 'spongebob',
      title: 'spongebob',
      description: 'spongebob',
    },
    {
      docId: 4,
      genre: 'children',
      slug: 'arthur',
      title: 'arthur',
      description: 'arthur',
    },
    {
      docId: 5,
      genre: 'children',
      slug: 'paw-patrol',
      title: 'paw-patrol',
      description: 'paw-patrol',
    },
    {
      docId: 6,
      genre: 'comedies',
      slug: 'arrested-development',
      title: 'arrested-development',
      description: 'arrested-development',
    },
    {
      docId: 7,
      genre: 'comedies',
      slug: 'curb-your-enthusiasm',
      title: 'curb-your-enthusiasm',
      description: 'curb-your-enthusiasm',
    },
    {
      docId: 8,
      genre: 'comedies',
      slug: 'family-guy',
      title: 'family-guy',
      description: 'family-guy',
    },
    {
      docId: 9,
      genre: 'comedies',
      slug: 'the-office',
      title: 'the-office',
      description: 'the-office',
    },
    {
      docId: 10,
      genre: 'comedies',
      slug: 'south-park',
      title: 'south-park',
      description: 'south-park',
    },
    {
      docId: 11,
      genre: 'crime',
      slug: 'long-shot',
      title: 'long-shot',
      description: 'long-shot',
    },
    {
      docId: 12,
      genre: 'crime',
      slug: 'making-a-murderer',
      title: 'making-a-murderer',
      description: 'making-a-murderer',
    },
    {
      docId: 13,
      genre: 'crime',
      slug: 'the-confession-killer',
      title: 'the-confession-killer',
      description: 'the-confession-killer',
    },
    {
      docId: 14,
      genre: 'crime',
      slug: 'the-innocent-man',
      title: 'the-innocent-man',
      description: 'the-innocent-man',
    },
    {
      docId: 15,
      genre: 'crime',
      slug: 'the-staircase',
      title: 'the-staircase',
      description: 'the-staircase',
    },
    {
      docId: 16,
      genre: 'documentaries',
      slug: 'amanda-knox',
      title: 'amanda-knox',
      description: 'amanda-knox',
    },
    {
      docId: 17,
      genre: 'documentaries',
      slug: 'citizenfour',
      title: 'citizenfour',
      description: 'citizenfour',
    },
    {
      docId: 18,
      genre: 'documentaries',
      slug: 'man-on-wire',
      title: 'man-on-wire',
      description: 'man-on-wire',
    },
    {
      docId: 19,
      genre: 'documentaries',
      slug: 'super-size-me',
      title: 'super-size-me',
      description: 'super-size-me',
    },
    {
      docId: 20,
      genre: 'documentaries',
      slug: 'tiger-king',
      title: 'tiger-king',
      description: 'tiger-king',
    },
    {
      docId: 21,
      genre: 'feel-good',
      slug: 'forrest-gump',
      title: 'forrest-gump',
      description: 'forrest-gump',
    },
    {
      docId: 22,
      genre: 'feel-good',
      slug: 'good-will-hunting',
      title: 'good-will-hunting',
      description: 'good-will-hunting',
    },
    {
      docId: 23,
      genre: 'feel-good',
      slug: 'juno',
      title: 'juno',
      description: 'juno',
    },
    {
      docId: 24,
      genre: 'feel-good',
      slug: 'midnight-in-paris',
      title: 'midnight-in-paris',
      description: 'midnight-in-paris',
    },
    {
      docId: 25,
      genre: 'feel-good',
      slug: 'school-of-rock',
      title: 'school-of-rock',
      description: 'school-of-rock',
    },
  ],
};
